platform :ios, '10.3'

target 'PePeP06' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PromiseKit'
  pod 'SwiftyBeaver'
  pod 'ObjectMapper'
  pod 'AWSCore'
  pod 'AWSS3'

  target 'PePeP06Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
